title: Madankui Tao
description: Personal website
author: Madankui Tao
email: mt3388@columbia.edu
phone: (917) 821-9063
github: https://github.com/taoma0528
about: I am a Ph.D. Student at Columbia University/Lamont Doherty Earth Observatory. 
disqus_shortname: programming
# google_analytics: UA-31048387-6
avatar_url: /static/img/me.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/madankui.tao/"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/madankui-tao-a6a4a9108/"
    - icon: fa-github
      link: "https://github.com/taoma0528"

urls:
    - text: About Me
      url: /about/
    - text: Research Projects
      url: /project/
    - text: Publications
      url: /publications/
    - text: Presentations
      url: /presentations/

# url: "http://localhost:4000"
# url: "https://tmjam.github.io/tauseef-blog"
url: "https://taoma0528.github.io/"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/blogs/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
